[terminal.shell]
  program = "wsl"
  args = ["--cd", "~"]
[font]
  normal = { family = "FiraCode Nerd Font Mono" }
  size = 14
[window]
  opacity = 0.9
  blur = true
  startup_mode = "Maximized"
  title = "Terminal"
  decorations_theme_variant = "Dark"
[cursor]
  style = { shape = "Block", blinking = "On" }